videoz/urls.py
from django.contrib import admin, auth
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from vids import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('dashboard', views.dashboard, name='dashboard'),
    # Auth
    path('signup', views.SignUp.as_view(), name='signup'),
    path('login', auth.views.LoginView.as_view(), name='login'),
    path('logout', auth.views.LogoutView.as_view(), name='logout'),
    # favories
    path('vids/list', views.full_list, name='list_faves'),
    path('vids/create', views.CreateFaves.as_view(), name='create_faves'),
    path('vids/<int:pk>', views.DetailFaves.as_view(), name='detail_faves'),
    path('vids/<int:pk>/update', views.UpdateFaves.as_view(), name='update_faves'),
    path('vids/<int:pk>/delete', views.DeleteFaves.as_view(), name='delete_faves'),
    # Videos
    path('video/<int:pk>/deletevideo',
         views.DeleteVideo.as_view(), name='delete_video'),
    path('vids/<int:pk>/addvideo', views.add_video, name='add_video'),
    path('vids/search', views.video_search, name='video_search'),

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

vids/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Favorites(models.Model):
    title = models.CharField(max_length=250)
    user = models.ForeignKey(User, on_delete=models.CASCADE)


class Video(models.Model):
    title = models.CharField(max_length=250)
    url = models.URLField()
    youtube_id = models.CharField(max_length=250)
    favorites = models.ForeignKey(Favorites, on_delete=models.CASCADE)

vids/forms.py
from .models import Video
from django import forms


class VideoForm(forms.ModelForm):
    class Meta:
        model = Video
        fields = ['url']
        labels = {'url': 'YouTube Url'}


class SearchForm(forms.Form):
    search_term = forms.CharField(
        max_length=225, label='Search for Videos', required=False)

vids/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login
from .models import Favorites, Video
from .forms import VideoForm, SearchForm
from django.http import Http404, JsonResponse
from django.forms.utils import ErrorList
import urllib
import requests
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from decouple import config

YOUTUBE_API_KEY = config('YOUTUBE_API_KEY')

# Create your views here.


def home(request):
    recent_faves = Favorites.objects.all().order_by('-id')[:3]
    # popular_faves = [Favorites.objects.get(pk=6), Favorites.objects.get(pk=7)]
    return render(request, 'vids/home.html', {'recent_faves': recent_faves})


@login_required
def dashboard(request):
    favorites = Favorites.objects.filter(user=request.user)
    return render(request, 'vids/dashboard.html', {'favorites': favorites})


def full_list(request):
    favorites = Favorites.objects.all().order_by('-id')
    return render(request, 'vids/list.html', {'favorites': favorites})


@login_required
def add_video(request, pk):
    form = VideoForm()
    search_form = SearchForm()
    faves = Favorites.objects.get(pk=pk)

    if not faves.user == request.user:
        raise Http404

    if request.method == 'POST':
        # Create
        form = VideoForm(request.POST)
        if form.is_valid():
            video = Video()
            video.favorites = faves
            video.url = form.cleaned_data['url']
            parsed_url = urllib.parse.urlparse(video.url)
            video_id = urllib.parse.parse_qs(parsed_url.query).get('v')
            if video_id:
                video.youtube_id = video_id[0]
                response = requests.get(
                    f'https://youtube.googleapis.com/youtube/v3/videos?part=snippet&id={video_id[0]}&key={YOUTUBE_API_KEY}')
                json = response.json()
                title = json['items'][0]['snippet']['title']
                video.title = title
                video.save()
                return redirect('dashboard')
            else:
                errors = form._errors.setdefault('url', ErrorList())
                errors.append('Needs to be a valid YouTube URL')

    return render(request, 'vids/add_video.html', {'form': form, 'search_form': search_form, 'faves': faves})


@login_required
def video_search(request):
    search_form = SearchForm(request.GET)
    if search_form.is_valid():
        encoded_search_term = urllib.parse.quote(
            search_form.cleaned_data['search_term'])
        response = requests.get(
            f'https://youtube.googleapis.com/youtube/v3/search?part=snippet&maxResults=6&q={encoded_search_term}&key={YOUTUBE_API_KEY}')

        return JsonResponse(response.json())

    return JsonResponse({'error': 'Not able to validate form'})


class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('dashboard')
    template_name = 'registration/signup.html'

    def form_valid(self, form):
        view = super(SignUp, self).form_valid(form)
        username, password = form.cleaned_data.get(
            'username'), form.cleaned_data.get('password1')
        user = authenticate(username=username, password=password)
        login(self.request, user)
        return view


class CreateFaves(LoginRequiredMixin, generic.CreateView):
    model = Favorites
    fields = ['title']
    template_name = 'vids/create.html'
    success_url = reverse_lazy('dashboard')

    def form_valid(self, form):
        form.instance.user = self.request.user
        super(CreateFaves, self).form_valid(form)
        return redirect('dashboard')


class DetailFaves(generic.DetailView):
    model = Favorites
    template_name = 'vids/detail.html'


class UpdateFaves(LoginRequiredMixin, generic.UpdateView):
    model = Favorites
    template_name = 'vids/update_faves.html'
    fields = ['title']
    success_url = reverse_lazy('dashboard')

    def get_object(self):
        favorites = super(UpdateFaves, self).get_object()
        if not favorites.user == self.request.user:
            raise Http404
        return favorites


class DeleteFaves(LoginRequiredMixin, generic.DeleteView):
    model = Favorites
    template_name = 'vids/delete_faves.html'
    success_url = reverse_lazy('dashboard')

    def get_object(self):
        favorites = super(DeleteFaves, self).get_object()
        if not favorites.user == self.request.user:
            raise Http404
        return favorites


class DeleteVideo(LoginRequiredMixin, generic.DeleteView):
    model = Video
    template_name = 'vids/delete_video.html'
    success_url = reverse_lazy('dashboard')

    def get_object(self):
        video = super(DeleteVideo, self).get_object()
        print(video)
        if not video.favorites.user == self.request.user:
            raise Http404
        return video

vids/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Askbootstrap">
    <meta name="author" content="Askbootstrap">
    <title>VidList - Video Streaming Website</title>
    <!-- Favicon Icon -->
    <link rel="icon" type="image/png" href="{% static '/assets/img/logo2.png' %}" />

    <link rel="stylesheet" type="text/css" href="{% static '/assets/vendor/bootstrap/css/bootstrap.min.css' %}" />
    <!-- Custom fonts for this template-->
    <link rel="stylesheet" type="text/css" href="{% static '/assets/vendor/fontawesome-free/css/all.min.css' %}" />
    <!-- Custom styles for this template-->
    <link rel="stylesheet" type="text/css" href="{% static '/assets/css/seventheme.css' %}" />
    <!-- Owl Carousel -->
    <link rel="stylesheet" type="text/css" href="{% static '/assets/vendor/owl-carousel/owl.carousel.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/assets/vendor/owl-carousel/owl.theme.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Quicksand&display=swap" rel="stylesheet" />
</head>

<body class="sidebar-toggled" id="page-top" style="font-family: 'Quicksand', sans-serif">
    <nav class="navbar navbar-expand navbar-light bg-white static-top osahan-nav sticky-top">
        &nbsp;&nbsp;
        <a class="navbar-brand mr-1" href="{% url 'home' %}"><img class="img-fluid" alt=""
                src="{% static 'assets/img/logo2.png' %}"></a>
        <ul class="navbar-nav ml-auto ml-md-0 osahan-right-navbar">
            {% if user.is_authenticated %}
            <li class="nav-item mx-1">
                <a class="nav-link" href="{% url 'create_faves' %}">
                    <i class="fas fa-plus-circle fa-fw"></i>
                    Create Playlist
                </a>
            </li>
            <li class="nav-item mx-1">
                <a class="nav-link" href="{% url 'dashboard' %}">
                    <i class="fas fa-fw fa-user-circle"></i>
                    Dashboard
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'list_faves' %}">
                    <i class="fas fa-fw fa-list-alt"></i>
                    <span>Playlists</span>
                </a>
            </li>
            <li class="nav-item mx-1">
                <a class="nav-link" href="{% url 'logout' %}">
                    <i class="fas fa-fw fa-sign-out-alt"></i>
                    Log Out
                </a>
            </li>
            {% else %}
            <li class="nav-item mx-1">
                <a class="nav-link" href="{% url 'login' %}">
                    <i class="fas fa-fw fa-sign-in-alt"></i>
                    Log In
                </a>
            </li>
            <li class="nav-item mx-1">
                <a class="nav-link" href="{% url 'signup' %}">
                    <i class="fas fa-envelope-square"></i>
                    Sign Up
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'list_faves' %}">
                    <i class="fas fa-fw fa-list-alt"></i>
                    <span>Playlists</span>
                </a>
            </li>
            {% endif %}
        </ul>
    </nav>
    <div id="wrapper">
        <!-- Sidebar -->
        <ul class="sidebar toggled navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'home' %}">
                    <i class="fas fa-fw fa-home"></i>
                    <span>Home</span>
                </a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link" href="{% url 'list_faves' %}">
                    <i class="fas fa-fw fa-list-alt"></i>
                    <span>Playlists</span>
                </a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'dashboard' %}">
                    <i class="fas fa-fw fa-user-alt"></i>
                    <span>Dashboard</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'create_faves' %}">
                    <i class="fas fa-fw fa-cloud-upload-alt"></i>
                    <span>Create Playlist</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'dashboard' %}">
                    <i class="fas fa-fw fa-video"></i>
                    <span>Add Video</span>
                </a>
            </li>
            {% endif %}

        </ul>
        <div id="content-wrapper">
            <div class="container-fluid pb-0">
                <div class="top-category section-padding mb-4">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="main-title">
                                <h6>Featured Playlists</h6>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="owl-carousel owl-carousel-category">
                                {% for playlist in all_faves %}
                                <div class="item">
                                    <div class="category-item">
                                        <a class="text-secondary" href="{% url 'detail_faves' playlist.id %}">
                                            <h6>{{ playlist.title }}</h6>
                                            <p>74,853 views</p>
                                        </a>
                                    </div>
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
                <hr>
                <!-- Bootstrap core JavaScript-->
                <script src="{% static 'assets/vendor/jquery/jquery.min.js' %}"></script>
                <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
                <!-- Core plugin JavaScript-->
                <script src="{% static 'assets/vendor/jquery-easing/jquery.easing.min.js' %}"></script>
                <!-- Owl Carousel -->
                <script src="{% static 'assets/vendor/owl-carousel/owl.carousel.js' %}"></script>
                <!-- Custom scripts for all pages-->
                <script src="{% static 'assets/js/custom.js' %}"></script>
                {% block content %}
                {% endblock %}
                <!-- Popular Faves -->
                <hr class="mt-0">
                <div class="video-block section-padding">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="main-title">

                            </div>
                            <h6>Popular Videos</h6>
                        </div>
                        {% for video in all_vids %}
                        <div class="col-xl-3 col-sm-6 mb-3">
                            <div class="video-card">
                                <div class="video-card-image">
                                    <iframe class="rounded" width="100%" height="181"
                                        src="https://www.youtube.com/embed/{{video.youtube_id}}" frameborder="0"
                                        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                                        allowfullscreen></iframe>
                                </div>
                                <div class="channels-card-body">
                                    <div class="channels-title">
                                        <a class="" href="#">
                                            <p class="text-truncate m-3">{{video.title}}</p>
                                        </a>
                                    </div>
                                    <div class="channels-view m-3">
                                        382,323 subscribers
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <!-- /.container-fluid -->
            <!-- Sticky Footer -->
            <!-- Sticky Footer -->
            <footer class="sticky-footer">
                <section class="section-padding footer-list">
                    <div class="container">
                        <div class="row">
                            <div class="col-lg-3 col-md-3">
                                <div class="footer-logo mb-4"><a class="logo" href="index.html"><img alt=""
                                            src="{% static 'assets/img/logo2.png' %}" class="img-fluid"></a></div>
                            </div>
                            <div class="col-lg-2 col-md-2">
                                <h6 class="mb-4">Company</h6>

                            </div>
                            <div class="col-lg-2 col-md-2">
                                <h6 class="mb-4">Features</h6>

                            </div>
                            <div class="col-lg-2 col-md-2">
                                <h6 class="mb-4">Solutions</h6>

                            </div>
                            <div class="col-lg-3 col-md-3">
                                <h6 class="mb-4">NEWSLETTER</h6>
                                <div class="input-group">
                                    <input type="text" class="form-control" placeholder="Email Address...">
                                    <div class="input-group-append">
                                        <button class="btn btn-primary" type="button"><i
                                                class="fas fa-arrow-right"></i></button>
                                    </div>
                                </div>
                                <small>It is a long established fact that a reader will be distracted by..</small>
                                <h6 class="mb-2 mt-4">DOWNLOAD APP</h6>
                                <p class="mb-0"><a href="#" class="text-dark"><i class="fas fa-envelope fa-fw"></i>
                                        iamosahan@gmail.com</a></p>
                                <p class="mb-0"><a href="#" class="text-dark"><i class="fas fa-globe fa-fw"></i>
                                        www.askbootstrap.com</a></p>
                                <div class="app">
                                    <a href="#"><img alt="" src="{% static 'assets/img/google.png' %}"></a>
                                    <a href="#"><img alt="" src="{% static 'assets/img/apple.png' %}"></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>

            </footer>
        </div>
        <!-- /.content-wrapper -->
    </div>
    <!-- /#wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'assets/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- Core plugin JavaScript-->
    <script src="{% static 'assets/vendor/jquery-easing/jquery.easing.min.js' %}"></script>
    <!-- Owl Carousel -->
    <script src="{% static 'assets/vendor/owl-carousel/owl.carousel.js' %}"></script>
    <!-- Custom scripts for all pages-->
    <script src="{% static 'assets/js/custom.js' %}"></script>
</body>

</html>

vids/templates/vids/add_video.html
{% extends 'base.html' %} {% block content %}
<div class="container">
  <h4>Add Video to {{ faves.title }}</h4>
  <form method="post" id="submit_video">
    {% csrf_token %}
    {% load widget_tweaks %}

    {% for field in form %}
    <div class="form-group {% if field.errors %} alert alert-danger {% endif %}">
      {{field.errors}}
      {{field.label_tag}}
      {% render_field field class="form-control" %}
    </div>
    {% endfor %}

    <button type="submit" class="btn btn-danger">Add</button>
  </form>
  <br>
  <h4>OR</h4>
  <form>
    {% for field in search_form %}
    <div class="form-group">
      {{field.errors}}
      {{field.label_tag}}
      {% render_field field class="form-control" %}
    </div>
    {% endfor %}
  </form>

  <div id="search_results">
    <script>
      let delayTimer;
      $('#id_search_term').keyup(function () {
        clearTimeout(delayTimer);
        $('#search_results').text('Loading...');
        delayTimer = setTimeout(function () {
          let text = $('#id_search_term').val();
          $.ajax({
            url: '/vids/search',
            data: {
              'search_term': text
            },
            dataType: 'json',
            success: function (data) {

              let results = '';
              $('#search_results').text('');

              results += '<div class="row">';
              data['items'].forEach((video) => {
                results += '<div class="col-md-4 mt-3"><div class="card mb-4 shadow-sm">';
                results += '<iframe width="100%" height="225" src="https://www.youtube.com/embed/' + video['id']['videoId'] + ' " frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>';
                results += '<div class="card-body"><p class="card-text text-truncate">' + video['snippet']['title'] + '</p>';
                results += '<a href="#" class="btn btn-danger" onclick="addVideo(\'' + video['id']['videoId'] + '\')">Add</a></div></div></div>';
              });
              results += '</div>';

              $('#search_results').append(results);
            }
          });
        }, 1000);
      });

      function addVideo(videoId) {
        $('#id_url').val('https://www.youtube.com/watch?v=' + videoId);
        $('#submit_video').submit();
        console.log('clicked')
      }
    </script>
  </div>
  <br>

</div>
{% endblock %}

vids/templates/vids/create.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h4>Create Playlist</h4>
    <form method="post">
        {% csrf_token %}
        {% load widget_tweaks %}
        {% for field in form %}
        <div class="form-group {% if field.errors %} alert alert-danger {% endif %}">
            {{field.errors}}
            {{field.label_tag}}
            {% render_field field class="form-control" %}
        </div>
        {% endfor %}
        <button type="submit" class="btn btn-danger">Create</button>
    </form>
</div>
<br>
{% endblock %}

vids/templates/vids/dashboard.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="text-center">
        <h4>{{ user.username }}'s Playlists</h4>
        <a href="{%url 'create_faves'%}" class="btn btn-danger">Create Playlist</a>
    </div>
    {% for faves in favorites %}
    <h6><a href="{% url 'detail_faves' faves.id %}" class="text-dark">
            {{ faves.title }}
        </a></h6>
    <a href="{% url 'delete_faves' faves.id%}" class="btn btn-dark">Delete List</a>
    <a href="{% url 'update_faves' faves.id%}" class="btn btn-secondary">Edit List</a>
    <a href="{% url 'add_video' faves.id%}" class="btn btn-danger">Add Video</a>
    <br><br>

    <div class="row">
        {% for video in faves.video_set.all %}
        <div class="col-md-3 mt-3">
            <div class="card mb-4 shadow-sm">
                <iframe width="100%" height="225" src="https://www.youtube.com/embed/{{video.youtube_id}}"
                    frameborder="0"
                    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                    allowfullscreen></iframe>
                <div class="card-body">
                    <p class="card-text text-truncate">{{video.title}}</p>
                    {% if user.id == faves.user.id %}
                    <a href="{% url 'delete_video' video.id %}" class="btn btn-dark ml=0 mt-2">Delete Video</a>
                    {% endif %}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

    {% endfor %}

</div>
<br>
{% endblock %}

vids/templates/vids/delete_faves.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <a href="{% url 'detail_faves' favorites.id %}">
        <h4>Delete Playlist {{favorites.title}}?</h4>
    </a>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="btn btn-danger">Delete</button>
    </form>
    <div class="row">
        {% for video in favorites.video_set.all %}
        <div class="col-md-3 mt-3">
            <div class="card mb-4 shadow-sm">
                <iframe width="100%" height="225" src="https://www.youtube.com/embed/{{video.youtube_id}}"
                    frameborder="0"
                    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                    allowfullscreen></iframe>
            </div>
        </div>
        {% endfor %}
    </div>
    <br>
</div>
{% endblock %}

vids/templates/vids/delete_video.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h2>Are You Sure You Want to Delete This Video?</h2>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="btn btn-danger">Delete</button>
    </form>

    <div class="row">
        <div class="col-md-4 mt-3">
            <div class="card mb-4 shadow-sm">
                <iframe width="100%" height="225" src="https://www.youtube.com/embed/{{video.youtube_id}}"
                    frameborder="0"
                    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                    allowfullscreen></iframe>
                <div class="card-body">
                    <p class="card-text">{{video.title}}</p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

vids/templates/vids/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <!--  ************************* Page Title Starts Here ************************** -->
    <div class="page-nav no-margin row">
        <div class="container">
            <div class="row">
                <h4>{{ favorites.title }}</h4>
            </div>
        </div>
    </div>

    <!--####################### Display Videos Here ###################-->
    <div class="container">
        {% if user.id == favorites.user.id %}
        <a href="{% url 'delete_faves' favorites.id%}" class="btn btn-dark">Delete List</a>
        <a href="{% url 'update_faves' favorites.id%}" class="btn btn-secondary">Edit List</a>
        <a href="{% url 'add_video' favorites.id%}" class="btn btn-danger">Add Video</a>
        {% endif %}
        <br><br>
        <div class="row">
            {% for video in favorites.video_set.all  %}
            <div class="col-xl-3 col-sm-6 mb-3">
                <div class="video-card">
                    <div class="video-card-image">
                        <iframe class="rounded" width="100%" height="181"
                            src="https://www.youtube.com/embed/{{video.youtube_id}}" frameborder="0"
                            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                            allowfullscreen></iframe>
                    </div>
                    <div class="video-card-body">
                        <div class="video-title">
                            <a class="text-truncate" href="#">
                                <p class="text-truncate">{{video.title}}</p>
                            </a>
                        </div>
                        <div class="video-page text-success">
                            {{ favorites.user.username }} <a title="" data-placement="top" data-toggle="tooltip"
                                href="#" data-original-title="Verified"><i
                                    class="fas fa-check-circle text-success"></i></a>
                        </div>
                        {% if user.id == favorites.user.id %}
                        <a href="{% url 'delete_video' video.id %}" class="btn btn-dark mt-2">Delete Video</a>
                        {% endif %}
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

<!-- <div class="card-body">
    <p class="card-text">{{video.title}}</p>
    {% if user.id == favorites.user.id %}
    <a href="{% url 'delete_video' video.id %}" class="btn btn-dark">Delete Video</a>
    {% endif %}
</div> -->

vids/templates/vids/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h6>Recent Playlists</h6>
<div class="video-block section-padding">
    {% for recent in recent_faves %}
    <a class="text-dark" href="{% url 'detail_faves' recent.id %}">
        <h5 class="text-capitalize font-weight-bold">{{ recent.title }}</h5>
        <p class="text-secondary">{{ recent.video_set.all | length }} videos</p>
    </a>
    <div class="row">
        {% for video in recent.video_set.all %}
        <div class="col-xl-3 col-sm-6 mb-3">
            <div class="video-card">
                <div class="video-card-image">
                    <iframe class="rounded" width="100%" height="181"
                        src="https://www.youtube.com/embed/{{video.youtube_id}}" frameborder="0"
                        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                        allowfullscreen></iframe>
                </div>
                <div class="video-card-body">
                    <div class="video-title">
                        <a class="text-truncate" href="#">
                            <p class="text-truncate">{{video.title}}</p>
                        </a>
                    </div>
                    <div class="video-page text-success">
                        {{video.favorites.user}} <a title="" data-placement="top" data-toggle="tooltip" href="#"
                            data-original-title="Verified"><i class="fas fa-check-circle text-success"></i></a>
                    </div>
                    <div class="video-view">
                        1.8M views &nbsp;<i class="fas fa-calendar-alt"></i> 1 day ago
                    </div>
                </div>
            </div>
        </div>

        {%  endfor %}
    </div>
    {% endfor %}
</div>
{% endblock %}

vids/templates/vids/update_faves.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h4>Edit Playlist</h4>
    <form method="post">
        {% csrf_token %}
        {% load widget_tweaks %}
        {% for field in form %}
        <div class="form-group {% if field.errors %} alert alert-danger {% endif %}">
            {{field.errors}}
            {{field.label_tag}}
            {% render_field field class="form-control" %}
        </div>
        {% endfor %}
        <button type="submit" class="btn btn-danger">Save</button>
        <a href="{% url 'delete_faves' favorites.id %}" class="btn btn-dark">Delete</a>
    </form>
    <div class="row">
        {% for video in favorites.video_set.all %}
        <div class="col-md-3 mt-3">
            <div class="card mb-4 shadow-sm">
                <iframe width="100%" height="225" src="https://www.youtube.com/embed/{{video.youtube_id}}"
                    frameborder="0"
                    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                    allowfullscreen></iframe>
            </div>
        </div>
        {% endfor %}
    </div>

</div>
<br>
{% endblock %}